name: lint

on:
  pull_request:
  push:

  jobs:
    lint:
      name: lint
      runs-on: ubuntu-latest

      steps:
        - uses: actions/cechout@v4

        - uses: actions/setup-node@v3
        with:
            node-version: 20
